language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cd Otus01
- mkdir bin
- cd bin
- cmake ..
- cmake --build .
- cmake --build . --target helloworld
- cmake --build . --target helloworld_lib
- cmake --build . --target test_version
- "./test_version"
- cd ../../
deploy:
  provider: bintray
  file: descriptor.json
  user: joy7701
  key:
    secure: ckYn035KZNHDaxacsw4eYWTZdttQln/11JZiolPDl56Ec8ivQTnVZFIAQ73FgvBY//X7MjbUQtXOloPLCUACiSyKQCBIVDFQE4GiRJKZvGrVQGH7DMMfNm8RLhR+1dJ5TohqFO3sZ0l26X7E4ydPZPy3Zwrkw9GkKkpxbFOZG5v/pP3xoAsCbbvArib52AMcmkWTLh9AjaVU/pPA8ibfK2wBntg8IfrCeUo/yvJETzwCZTZs6n6YDmaklCEqbOBG6FxVfKPm5S+PN+FglhkHkr2KGPUPmtM4WmiFo+Gj/xXZ8WU4lqw63cxyaphgDYUtefKiYw2IFMeEu1D1Cfa3SCs7tiVIQQBv2PBdRV9uimavdjJ5z1+o7BjqXe8vwgVNYOITmWSGxaWt7Uxp0pFeQE+I5FyjgZuQ23Ge2AyUYty3DPgtlxFoNhIvRdGXIt33HQgdU1ZXz83hNVdknL66auF4/P2Nbude+tVoEhk5RE0Rb3isplzIlNt7wtpFrN/0oR3asEpB8T/3pW58f0+ge37HBXsQsvofeD/y+hGJM9urecqyaFr68HHBnrvQtR1lJnhgOXrlaX6HV385x9RTnIDQisj27swjyLKGVlnVBao659/ukC+8n3vaBiIQbTovS5cn/BWcbm2/t546K2uwndbPkcWGBzk9JB+KhVoJE4A=
  skip-cleanup: true
