language: cpp
os: linux
dist: xenial
before_script:
- sudo apt-get install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- envsubst '${TRAVIS_BUILD_VERSION}' < bintray-conf.json | tee bintray-conf.json
- cd Otus01
- mkdir bin
- cd bin
- cmake ..
- cmake --build .
- cmake --build . --target helloworld
- cmake --build . --target helloworld_lib
- cmake --build . --target test_version
- "./test_version"
- cd ../../
deploy:
  provider: bintray
  file: ./bintray-conf.json
  user: joy7701
  cleanup: false
  skip_cleanup: true
  key:
    secure: 1tFIA41CG5I5C2RH+Vixr9k8I6JIQRgHcfhNtudQnK5La2Mocu5RS9RnYL7F4Shur1JDAETVzpqYqYwjHhW5POgLLG+jrgstcAeraMDvaMfuXlNnYEaorJXQDlYiA7y4L3X8HoDqHmzU7LMquX9AJvrOVe1YaoOC116/5rdy6815NaiFhzlO6f5oVwp7VI16ghPCicRcResYTcp7yOEISlwq4YSSJC3tR3ebQrOQVJFjBvsyv497SykKw72ZCz445F/EMpI2WSxa1ij+PKrJmoxXL9Hxj5pRiAk56qDMfQfyBl1WFGw3cKGbKDHhl8U5Z5zEDtkNRuNEachH8wbj73B/RgoMHRF5CuL3XJJkmkXj+dcF6GhQpNV5PvBCcCFv+2PfbiZyFj4FpFO5hyCXswLQd0Jt0bdef+ZQBxwUX73zGXbnz0j74Buxoxa4X1LOTE9ti0/MDo0T4ogSUDJ/Psm+pxWILNsysNdOsk1AVPwUdk7A0KjWEhckrkOGPBSavjeOVQa8yc5Izgh0q928basdxXBkkHqFxcFS2Q3H55hVgNOy8QGZMJaW/s6V5qcQDgr+hEgT/rh9kMx+Yrta0nRA60wTth5hv7UyyVJ8lFvDAKENwMnjUzn7yhnLoNjcbDACJs23VIylmqc29xANLZhTD1ly5aIrdcrr4ohZeVA=
